version: "3.8"
volumes:
  mysql-data:
services:
  php:
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: ./environment/Dockerfile
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql